#!/usr/bin/env bash
# Append tailnet peer names (generated by the vivary CLI at start) to
# /etc/hosts. Runs as root via the sudoers entry; idempotent.
set -u
SRC=/home/agent/.config/tailscale-hosts
[ -f "$SRC" ] || exit 0
while read -r line; do
    [ -n "$line" ] || continue
    grep -qF "$line" /etc/hosts || echo "$line" >> /etc/hosts
done < "$SRC"
